travis:
  secure:
    BINSTAR_TOKEN: Vgktv/ybyqUJfCT6cGAEmhLJBJTddm4EFI8rZ8RozhjHtIAjDPeGl4gygSc74+XNrD29SJTyX2sHeXYCqMQLRBlieWht/TV2gnDPN1oo2+Y30fxbeVBIBgdICJN5n33Igzks8ekuznPktTenxc5I2zcY5NooFmiKHhBbgsGxzO8qERjHTq1eErdKg80n/Dvx4dFtYjAR3k1JW1yvxH7Qxl3vXCyNLx9tYujNItcrYYROacf6lUCMYBbMFq42ZHWlDGoWM9qIxIY3aegUVowyB3JPirNRhGG3MH/jxRWvZspjwrpHe0+pZ4POKzTM2yn2IiFPBxtxBNnecsChSwRF1yMv7EOUxPqoDgtVGMhQnsqMIwDqiJEIxb5gn/VpTw9s1qrqKBTg+h8vcKI6ylZjfJsG00SIRMDzmNujY8ZTfJOoHS3kEdLzVnx76ugjA5gJ+xuegm3bKrfIyy5luTISOa7yHk17hUeArU05ycX1k5yaoYw1cQ1pB6zeDkJ621SOwI+Ba4SLKD7K657QcMfaWrC47MwBDlB3UWT+ofjzq8u9Fl/q0deCW8Cg4tYuZ8SkjOxgvIJKcNC4srz2ur/h8VQC7AfViH7D2NrjvqaJBnIU0xbdUd5C4Z+5yektfZAo8UOb8wE4Y36hoClJUKdgpRFLTDu2fPptT4SDL8i75qM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
